name: Bug Report
description: Something isn't working correctly with MJML Signoff
title: 'bug: '
labels: 'Type: Bug'
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behavior in the existing issues. **Security note: If you're reporting a vulnerability or other security issue, please see [https://premail.dev/security/](https://premail.dev/security/) for the procedure.**

        ---

        Thank you for taking the time to file a bug report! To address this bug as fast as possible, we need some information.
  - type: input
    id: v_mjml_signoff
    attributes:
      label: MJML Signoff version
      description:
        'Run `npm list mjml-signoff` or `yarn list mjml-signoff` and paste the
        first line of the output with `mjml-signoff` here.'
    validations:
      required: true
  - type: input
    id: v_mjml
    attributes:
      label: MJML version
      description:
        'Run `npm list mjml` or `yarn list mjml` and paste the first line of the
        output with `mjml` here.'
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Linux
        - Mac
        - Windows
    validations:
      required: true
  - type: input
    id: v_node
    attributes:
      label: Node version
      description: 'Run `node --version` and paste the output here.'
    validations:
      required: true
  - type: input
    id: v_package_manager
    attributes:
      label: NPM or Yarn version
      description:
        "Run `npm --version` or `yarn --version` (depending on which you're
        using) and paste the output here."
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: Describe how the bug shows up.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe what you expect the behavior to be without the bug.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Explain the steps required to duplicate the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description:
        If applicable, provide relevant log output. No need for backticks here.
      render: shell
  - type: textarea
    id: related_code
    attributes:
      label: Related code
      description:
        If you can point to a file or lines in the existing code relevant to
        this bug, please do.
  - type: textarea
    id: solution
    attributes:
      label: Preferred solution
      description:
        If you have a suggested technical solution to this bug, please describe
        it here.
  - type: textarea
    id: other_info
    attributes:
      label: Other information
      description:
        Any other information that might be relevant to this bug such as what
        kind of build system you're using or in what contexts the bug is
        appearing.
  - type: markdown
    attributes:
      value: |
        ---

        **Thank you!**
